### ISSUE TITLE
#TODO

### ISSUE THREAD

**Issue by ilarialauzana** [ilarialauzana/AppVizData#1]
- [ ] Add plotting

- [ ] Add list of trials for which we have also handtracking

- [ ] Create web app

- [ ] Publish on SAHR website
